# Generated by Django 4.2.3 on 2023-09-01 05:22

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('detail', models.CharField(max_length=5000)),
                ('main_picture', models.ImageField(null=True, upload_to='')),
                ('end_location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_location_end', to='app.location')),
                ('start_location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_location_start', to='app.location')),
                ('tour_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_guide', to=settings.AUTH_USER_MODEL, validators=[app.models.check_role])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TourStartDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(null=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourstartdate_tourid', to='app.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicle_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_vehicle', to='app.vehicle'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(null=True)),
                ('activity', models.CharField(max_length=5000, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('heading', models.CharField(max_length=200, null=True)),
                ('tour_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tourid', to='app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField(null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('star', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_accid', to=settings.AUTH_USER_MODEL)),
                ('tour_startdate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_tourstartdateid', to='app.tourstartdate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tourstartdate',
            constraint=models.UniqueConstraint(fields=('tour_id', 'start_date'), name='unique_migration_tourstartdate'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('tour_id', 'date'), name='unique_migration_schedule'),
        ),
    ]
