# Generated by Django 4.2.2 on 2023-08-10 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('detail', models.CharField(max_length=500)),
                ('tag', models.CharField(choices=[('s', 'Sap dien ra'), ('d', 'Dang dien ra'), ('k', 'Da ket thuc')], default='Sap dien ra', max_length=30)),
                ('end_location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_location_end', to='app.location')),
                ('start_location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_location_start', to='app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicel_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TourStartDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(null=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourstartdate_tourid', to='app.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicel_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_vehicle', to='app.vehicel'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('activity', models.CharField(max_length=500, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_locationid', to='app.location')),
                ('tour_startdate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tourstartdateid', to='app.tourstartdate')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_tour', to='app.tour')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tourstartdate',
            constraint=models.UniqueConstraint(fields=('tour_id', 'start_date'), name='unique_migration_tourstartdate'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('tour_startdate_id', 'date'), name='unique_migration_schedule'),
        ),
    ]
