# Generated by Django 4.2.3 on 2023-07-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('tg', 'Huong dan vien'), ('us', 'Nguoi dung')], default='Nguoi dung', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('detail', models.CharField(max_length=500)),
                ('tag', models.CharField(choices=[('s', 'Sap dien ra'), ('d', 'Dang dien ra'), ('k', 'Da ket thuc')], default='Sap dien ra', max_length=30)),
                ('end_location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_location_end', to='app.location')),
                ('start_location_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_location_start', to='app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicel_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TourStartDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(null=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourstartdate_tourid', to='app.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='vehicel_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_vehicle', to='app.vehicel'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('activity', models.CharField(max_length=500, null=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_locationid', to='app.location')),
                ('tour_startdate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tourstartdateid', to='app.tourstartdate')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register_date', models.DateField(null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('star', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_accid', to='app.account')),
                ('tour_startdate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_tourstartdateid', to='app.tourstartdate')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('tg', 'Huong dan vien'), ('us', 'Nguoi dung')], default='Nguoi dung', max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('m', 'Nam'), ('w', 'Nu')], default='Nam', max_length=30)),
                ('phone_num', models.CharField(max_length=10)),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_accountid', to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_tour', to='app.tour')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tourstartdate',
            constraint=models.UniqueConstraint(fields=('tour_id', 'start_date'), name='unique_migration_tourstartdate'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('tour_startdate_id', 'date'), name='unique_migration_schedule'),
        ),
        migrations.AddConstraint(
            model_name='register',
            constraint=models.UniqueConstraint(fields=('tour_startdate_id', 'acc_id'), name='unique_migration_register'),
        ),
    ]
