# Generated by Django 4.2.3 on 2023-07-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("location_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicel_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tour_name", models.CharField(max_length=100)),
                ("price", models.IntegerField(null=True)),
                ("time", models.IntegerField(null=True)),
                ("detail", models.CharField(max_length=500)),
                (
                    "end_location_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_location_end",
                        to="app.location",
                    ),
                ),
                (
                    "start_location_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_location_start",
                        to="app.location",
                    ),
                ),
                (
                    "vehicel_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_vehicle",
                        to="app.vehicel",
                    ),
                ),
            ],
        ),
    ]
