# Generated by Django 4.2.3 on 2023-08-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('activity', models.CharField(max_length=500, null=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('heading', models.CharField(max_length=200, null=True)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_tourid', to='app.tour')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('tour_id', 'date'), name='unique_migration_schedule'),
        ),
    ]
