# Generated by Django 4.2.3 on 2023-08-19 05:39

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_register"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedule",
            name="unique_migration_schedule",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="tour_startdate_id",
        ),
        migrations.AddField(
            model_name="register",
            name="tour_guide",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_guide",
                to=settings.AUTH_USER_MODEL,
                validators=[app.models.check_role],
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="heading",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="tour_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_tourid",
                to="app.tour",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("tour_id", "date"), name="unique_migration_schedule"
            ),
        ),
    ]
