# Generated by Django 4.2.3 on 2023-07-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_tour_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourStartDate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField(null=True)),
                (
                    "tour_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourstartdate_tourid",
                        to="app.tour",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("picture", models.ImageField(null=True, upload_to="")),
                (
                    "tour_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picture_tour",
                        to="app.tour",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tourstartdate",
            constraint=models.UniqueConstraint(
                fields=("tour_id", "start_date"), name="unique_migration_tourstartdate"
            ),
        ),
    ]
