# Generated by Django 4.2.3 on 2023-08-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_schedule_unique_migration_schedule_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Register",
        ),
    ]
