# Generated by Django 4.2.3 on 2023-08-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schedule_schedule_unique_migration_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='detail',
            field=models.CharField(max_length=5000),
        ),
    ]
