# Generated by Django 4.2.3 on 2023-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tour_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='activity',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
