# Generated by Django 4.2.3 on 2023-08-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_schedule_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
