# Generated by Django 4.2.3 on 2023-08-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="star",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
    ]
