# Generated by Django 4.2.3 on 2023-07-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name_user", models.CharField(max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[("tg", "Huong dan vien"), ("us", "Nguoi dung")],
                        default="Nguoi dung",
                        max_length=30,
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Nam"), ("w", "Nu")],
                        default="Nam",
                        max_length=30,
                    ),
                ),
                ("phone_num", models.CharField(max_length=10)),
                ("avatar", models.ImageField(null=True, upload_to="")),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_accountid",
                        to="app.account",
                    ),
                ),
            ],
        ),
    ]
