# Generated by Django 4.2.3 on 2023-07-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("register_date", models.DateField(null=True)),
                ("comment", models.CharField(max_length=200, null=True)),
                (
                    "start",
                    models.IntegerField(
                        choices=[("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5)],
                        default=5,
                    ),
                ),
                (
                    "acc_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_accid",
                        to="app.account",
                    ),
                ),
                (
                    "tour_startdate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register_tourstartdateid",
                        to="app.tourstartdate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="register",
            constraint=models.UniqueConstraint(
                fields=("tour_startdate_id", "acc_id"), name="unique_migration_register"
            ),
        ),
    ]
