# Generated by Django 4.2.3 on 2023-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_register_register_unique_migration_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="start",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
    ]
