# Generated by Django 4.2.3 on 2023-08-30 16:49

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0008_alter_register_star"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="tour_guide",
        ),
        migrations.AddField(
            model_name="tour",
            name="tour_guide",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tour_guide",
                to=settings.AUTH_USER_MODEL,
                validators=[app.models.check_role],
            ),
        ),
    ]
