# Generated by Django 4.2.3 on 2023-08-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_schedule_schedule_unique_migration_schedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
