# Generated by Django 4.2.3 on 2023-08-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_schedule_schedule_unique_migration_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="location_id",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.IntegerField(null=True),
        ),
    ]
