# Generated by Django 4.2.3 on 2023-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_schedule_location_id_alter_schedule_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="heading",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
