# Generated by Django 4.2.3 on 2023-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_schedule_heading"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vehicel",
            new_name="Vehicle",
        ),
        migrations.RenameField(
            model_name="tour",
            old_name="vehicel_Id",
            new_name="vehicle_Id",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="vehicel_name",
            new_name="vehicle_name",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="tag",
        ),
        migrations.AddField(
            model_name="schedule",
            name="picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="tour",
            name="main_picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
    ]
