# Generated by Django 4.2.3 on 2023-08-08 14:41

from django.db import migrations, models
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Min 3 char and max 30 char. No special characters allowed', max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(help_text='Min 3 char and max 30 char. No special characters allowed', max_length=30, validators=[users.validators.PasswordValidator()], verbose_name='password')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('TG', 'Hướng dẫn viên'), ('USER', 'Khách hàng')], default='Khách hàng', max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('W', 'Nữ')], default='Nam', max_length=30)),
                ('phone', models.CharField(help_text='Số điện thoại là số có 10 chữ số', max_length=10, validators=[users.validators.PhoneValidator()])),
                ('avatar', models.FileField(null=True, upload_to='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
