# Generated by Django 4.2.2 on 2023-08-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(help_text='Min 3 char and max 30 char. No special characters allowed', max_length=30, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(help_text='Số điện thoại là số có 10 chữ số', max_length=10),
        ),
    ]
