# Generated by Django 4.2.3 on 2023-08-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(help_text='Min 3 char and max 30 char. No special characters allowed', max_length=100, verbose_name='password'),
        ),
    ]
